---
title: Como você design for good?
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
baseurl: ""
author: Avelar Fortunato
email: comovocedesign@gmail.com
description: Podcast com entrevistas de designers que fazem a diferença
exclude:
- README.md
- Gemfile.lock
- vendor
